openapi: 3.0.3
info:
  title: Demo API
  version: 1.0.0
  description: API de ejemplo (solo docs).
paths:
  /ping:
    get:
      summary: Devuelve pong (solo documentado)
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: { "message": "pong" }
